"""jwt token added

Revision ID: 54d9aa5ce0f9
Revises: 558d879c66a9
Create Date: 2025-10-25 21:51:57.321356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54d9aa5ce0f9'
down_revision: Union[str, Sequence[str], None] = '558d879c66a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenblacklist_id'), 'tokenblacklist', ['id'], unique=False)
    op.create_index(op.f('ix_tokenblacklist_token'), 'tokenblacklist', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenblacklist_token'), table_name='tokenblacklist')
    op.drop_index(op.f('ix_tokenblacklist_id'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###
