"""contact feature

Revision ID: d0d8ec6878cd
Revises: 02672e6fce4f
Create Date: 2025-11-11 17:00:29.559179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0d8ec6878cd'
down_revision: Union[str, Sequence[str], None] = '02672e6fce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.add_column('phone', sa.Column('contact_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('phone_user_id_fkey'), 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'contact', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_column('phone', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key(op.f('phone_user_id_fkey'), 'phone', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('phone', 'contact_id')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
