"""user-contact backpopulate fixed

Revision ID: d50a871cc6a4
Revises: d0d8ec6878cd
Create Date: 2025-11-11 17:07:44.295847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd50a871cc6a4'
down_revision: Union[str, Sequence[str], None] = 'd0d8ec6878cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'user_id')
    # ### end Alembic commands ###
